spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3307/social_media
    username: appuser
    password: apppassword
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/*.xml   # ← 對應 resources/mappers/
  type-aliases-package: com.example.demo.model.my
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: secret-key-secret-key-secret-key-secret-key
  expiration: 86400000